#Properties Config file
#Mon Aug 24 22:14:00 CST 2026
motd=§a§lSERVER BLUE
server-port=19132
white-list=off
announce-player-achievements=on
spawn-protection=0
max-players=10000
allow-flight=off
spawn-animals=on
spawn-mobs=on
gamemode=0
force-gamemode=off
hardcore=off
pvp=on
difficulty=1
generator-settings=
level-name=world
level-seed=
level-type=FLAT
enable-query=on
enable-rcon=off
rcon.password=E6ZJIWA9Lj
auto-save=on
server-prefix=&8[&cD§bW&8]
op-password=1weubafwy6hx1349443ml677
online-mode=off
